name: 'Mark or Close Stale Issues and PRs'

on:
  workflow_call:  # This makes it a shared workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Stale issues and PRs after 30 days
          days-before-stale: 30
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open for 30 days
            with no activity. Remove stale label or comment, or this issue will be closed in 10 days.
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open for 30 days
            with no activity. Remove stale label or comment, or this PR will be closed in 10 days.
          # Do not mark as stale if these labels exist
          exempt-issue-labels: bug,wip,on-hold
          exempt-pr-labels: bug,wip,on-hold
          exempt-all-milestones: true
          # Close issues and PRs after 10 more days
          days-before-close: 10
          delete-branch: true
          close-issue-message: This issue was automatically closed due to inactivity.
          close-pr-message: This PR was automatically closed due to inactivity.
